version: "1"

services:
  database:
    image: mysql:8.0.28
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: worldskills
      MYSQL_USER: worldskills
      MYSQL_PASSWORD: worldskills